#!/bin/bash
set -e

echo "installing oh my zsh..."
if [ -d ~/.oh-my-zsh ]; then
  echo "it looks like oh my zsh is already installed. doing nothing."
else
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

echo "linking .zshrc..."
rm -f ~/.zshrc
ln -sf "$HOME/.dotfiles/.zshrc" ~/.zshrc

echo "creating $HOME/src..."
mkdir -p "$HOME/src"
echo "creating $HOME/bractlet..."
mkdir -p "$HOME/bractlet"

echo "installing nvm..."
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash

echo "install latest LTS version of node using nvm..."
export NVM_DIR=$HOME/.nvm;
source $NVM_DIR/nvm.sh;
nvm install --lts

echo "install yarn..."
npm install --global yarn
