#!/bin/bash
set -e

echo "installing oh my zsh..."
if [ -d ~/.oh-my-zsh ]; then
  echo "it looks like oh my zsh is already installed. doing nothing."
else
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
